name: Random Versions

on:
  pull_request:

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "**requirements*.txt"
      - name: install package
        run: uv pip install -e . --system
      - name: generate-random-versions
        run: python utils/generate_random_versions.py
      - name: install-reqs
        run: uv pip install --upgrade tox virtualenv setuptools --system && uv pip install -r requirements-dev.txt --system
      - name: uninstall scipy/sklearn
        run: uv pip uninstall scipy scikit-learn --system
      - name: install-random-verions
        run: uv pip install -r random-requirements.txt --system
      - name: show versions
        run: uv pip freeze
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests --cov-fail-under=80
